### ISSUE TITLE
Example code does not work: max7219.lua:70: bad argument #1 to 'ipairs' (table or rotable expected, got nil)

### ISSUE THREAD

**Issue by tricoos** [marcelstoer/nodemcu-max7219#9]
The example code does not work:

```
[MAX7219] number of modules: 4, SS pin: 8
max7219.lua:70: bad argument #1 to 'ipairs' (table or rotable expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	max7219.lua:70: in function '?'
	max7219.lua:177: in function 'write'
	summy2.lua:3: in main chunk
	[C]: in function 'dofile'
	stdin:1: in main chunk
```

NodeMCU version:
```
NodeMCU custom build by frightanic.com
	branch: master
	commit: 22e1adc4b06c931797539b986c85e229e5942a5f
	SSL: false
	modules: bit,bme280,cjson,file,gpio,i2c,mqtt,net,node,spi,tmr,u8g,uart,wifi
 build 	built on: 2017-04-17 16:21
 powered by Lua 5.1.4 on SDK 2.0.0(656edbf)
```

**Comment by marcelstoer** [comment]
Which example? The one from https://github.com/marcelstoer/nodemcu-max7219/blob/master/README.md?
How does `summy2.lua:3` look?

**Comment by tricoos** [comment]
The official example code - summy2.lua (which should be called dummy2.lua btw) just contains the first lines of the example:

```
max7219 = require("max7219")
max7219.setup({debug = true, numberOfModules = 4, slaveSelectPin = 8})
max7219.write({
    { 0x20, 0x74, 0x54, 0x54, 0x3C, 0x78, 0x40, 0x00 },
    { 0x41, 0x7F, 0x3F, 0x48, 0x48, 0x78, 0x30, 0x00 },
    { 0x38, 0x7C, 0x44, 0x44, 0x6C, 0x28, 0x00, 0x00 },
    { 0x30, 0x78, 0x48, 0x49, 0x3F, 0x7F, 0x40, 0x00 }
  }, { rotate = "left" })
```

This in conjunction with the latest max7219.lua from the repo leads to this error.

**Comment by marcelstoer** [comment]
I know that it worked when I last tested. Might be that the changes I pulled in from someone else's fork (45e4460c4bb3b4ae008e7a01111d768d453810a9) broke something.

**Comment by tricoos** [comment]
I could fix it by changing the code to
```lua
local c = {}
  for i,char in pairs(chars) do 
  --for i = 1, #chars do
  --  local char = chars[i]
    if transformation.rotate ~= nil then
--      char = rotate(char, transformation.rotate == "left")
    end
```
However, I still couldn't get it to work with CS connected to D8 (the default in the example) - both displays (I have connected two right now) had all LEDs turned on and nothing could change that. It also locked up the USB connection to the PC (ESPlorer). After connecting CS to D2 and changing it in the code (slaveSelectPin = 2) it works now perfectly.

**Comment by marcelstoer** [comment]
I can't reproduce any of this, works just fine over here.

Furthermore, I find  you initial stacktrace a bit odd:
```
max7219.lua:70: in function '?'
max7219.lua:177: in function 'write'
```

[Line 70](https://github.com/marcelstoer/nodemcu-max7219/blob/45e4460c4bb3b4ae008e7a01111d768d453810a9/max7219.lua#L70) accesses the char passed to `rotate()` as a parameter. It seems to be nil so it was missing upon invocation.
Your stack trace says `rotate()` was called from [line 177](https://github.com/marcelstoer/nodemcu-max7219/blob/45e4460c4bb3b4ae008e7a01111d768d453810a9/max7219.lua#L177) but that can't be. The actual invocation is further down on line 180. Be that as it may it looks as if `max7219. write ()` wasn't passed any characters.
